---
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.6
    container_name: zookeeper
    networks:
       kafka:
          aliases:
            - zookeeper.local
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGLEVEL: ERROR
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-txn-logs:/var/lib/zookeeper/log
    
  broker:
    image: confluentinc/cp-enterprise-kafka:7.2.6
    container_name: broker
    networks:
       kafka:
          aliases:
            - broker.local
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGLEVEL: ERROR
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.local:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker.local:19092
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker.local:19092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper.local:22181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./secrets:/etc/kafka/secrets

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.6
    depends_on:
      - zookeeper
      - broker
    container_name: schema-registry
    networks:
       kafka:
          aliases:
            - schema-registry.local
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker.local:19092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry.local
      SCHEMA_REGISTRY_LISTENERS: "https://schema-registry.local:8081"
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "https"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_LOG4J_LOGLEVEL: ERROR
    volumes:
      - ./secrets:/etc/kafka/secrets

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.6
    container_name: control-center
    networks:
       kafka:
          aliases:
            - control-center.local
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_LOG4J_ROOT_LOGLEVEL: INFO
      CONTROL_CENTER_LOG4J_LOGLEVEL: INFO
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker.local:19092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper.local:22181
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "https://schema-registry.local:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REST_LISTENERS: "http://0.0.0.0:9021"
      PORT: 9021
    volumes:
      - ./secrets:/etc/kafka/secrets

  kafka-tools:
    image: confluentinc/cp-enterprise-kafka:7.2.6
    depends_on:
      - broker
    container_name: kafka-tools
    networks:
       kafka:
          aliases:
            - kafka-tools.local
    environment:
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
    volumes:
      - ./secrets:/etc/kafka/secrets
      - ./config:/etc/kafka/config

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.2.6
    depends_on:
      - zookeeper
      - broker
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    networks:
       kafka:
          aliases:
            - rest-proxy.local
    environment:
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_REST_LOG4J_LOGLEVEL: ERROR
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: broker.local:19092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper.local:22181
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
    volumes:
      - ./secrets:/etc/kafka/secrets

volumes:
  zk-data:
    external: true
  zk-txn-logs:
    external: true
  kafka-data:
    external: true

networks:
  kafka:
